project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - images/nn_logo-kurz_SCHWARZ.png
    - images/nn_logo-kurz_WEISS.png

website:
  title: ""
  favicon: images/favicon.png
  site-url: https://www.naturenoise.de
  navbar:
    collapse: false
    search: false
    left:
      - text: "<img src='images/nn_logo-kurz_WEISS.png' alt='naturenoise' class='navbar-logo' />"
        href: "#start"
      - text: konzerte
        href: "#konzerte"
      - text: medien
        href: "#medien"
      - text: kontakt
        href: "#kontakt"

  page-footer:
    center: 
      - text: "Feinste A Capella Musik seit 2009<br>naturenoise | 2026"

format:
  html:
    theme: flatly
    email-obfuscation: javascript
    smooth-scroll: true
    css: styles.css
    toc: false
    metadata:
      og:title: "naturenoise"
      og:description: "Feinste A Capella Musik seit 2009"
      og:image: "https://www.naturenoise.de/images/og-image.jpg"
      og:type: website
      twitter:card: summary_large_image

editor: visual
